[serve]
# The address to serve on LAN.
address = "127.0.0.1"
# The address to serve on WAN.
# address = "0.0.0.0"
# The port to serve on.
port = 8000
no_cache = true

[[proxy]]
backend = "http://127.0.0.1:3000/api/"

[[proxy]]
backend = "http://127.0.0.1:3000/static/"

